### ISSUE TITLE
top_moves returning empty list stockfish 15

### ISSUE THREAD

**Issue by m-sarabi** [zhelyabuzhsky/stockfish#113]
For stockfish 15, running `get_top_moves` returns an empty list.

### Reason:
models.py line 555 checks for depth value in integer, but `current_line` values are string, so this condition always results in being False and breaks the loop, returning an empty list.

### My Solution
Change line 555 from:
`and current_line[current_line.index("depth") + 1] == self.depth`
to
`and current_line[current_line.index("depth") + 1] == str(self.depth)`

I don't know if this would work on older versions though.

**Comment by johndoknjas** [comment]
Hi @m-sarabi thanks for the feedback. I don't think line 555 is a bug though, since self.depth is actually stored as a string itself. When the user passes an int for depth to the constructor (or the set_depth function), this argument is then converted to a string and stored in self.depth. Maybe it would be better practice to represent self.depth as an int in the future though, especially since it's technically a "public" field right now (so users might access it without knowing it's a string).

For why you get an empty list, would you mind giving the FEN of the position you tested the function with?

**Comment by m-sarabi** [comment]
So I see where the problem is. I was setting the depth manually by `stockfish.depth = 20` and it caused the issue as it is not predicted, and it was intuitive for me to set it as an int.

For the FEN position, it was the starting position.

#114 is the perfect solution for this. Closing this.
