### ISSUE TITLE
Compatibility with chess library

### ISSUE THREAD

**Issue by jamesbraza** [zhelyabuzhsky/stockfish#129]
There is another chess library https://github.com/niklasf/python-chess (aka `chess`) in existence, and it's popular and actively supported.  It also can integrate with Stockfish:

```python
import chess
import chess.engine

STOCKFISH_PATH = "/opt/homebrew/bin/stockfish"

board = chess.Board()

engine = chess.engine.SimpleEngine.popen_uci(STOCKFISH_PATH)
engine.configure({"UCI_LimitStrength": True, "UCI_Elo": 1600})
result = engine.play(board, limit=chess.engine.Limit(time=0.1))
board.push(result.move)
```

There is no acknowledgement of `chess` in the `README.md` or issue tracker, from what I can see.

This is an open-ended ticket sort of about:
- Acknowledging the existence of `chess` -- what makes this library different or better?
    - For example, I like your benchmarking support, and more complete wrapper
- Possibly make this package compatible with `chess` such that it can (1) accept `chess.Board` and pass to Stockfish, or (2) take a board from Stockfish and pass to a `chess.Board`.  A MVP solution could be to use Forsyth–Edwards Notation:

```python
import chess
from stockfish import Stockfish

STOCKFISH_PATH = "/opt/homebrew/bin/stockfish"

stockfish = Stockfish(path=STOCKFISH_PATH)
board = chess.Board()
stockfish.set_fen_position(fen_position=board.fen())
```

**Comment by kieferro** [comment]
Hello, this project is no longer maintained in this repo but on [this fork](https://github.com/py-stockfish/stockfish). (For more information about this please look [here](https://github.com/zhelyabuzhsky/stockfish/issues/130)).
Since this issue has no comments, it should be quite easy to copy the content and title into a [new issue over there](https://github.com/py-stockfish/stockfish/issues/new). (For more specific information on that, look [here](https://github.com/zhelyabuzhsky/stockfish/issues/130#user-content-issues)).
This makes it easier for us to keep track of things, and it's more convenient because we then have the issues right where they are being worked on. So please create a new issue in the new repo and then close this one. Thank you!

**Comment by jamesbraza** [comment]
Okay I see, thank you @kieferro!  I have migrated the issue to https://github.com/py-stockfish/stockfish/issues/6.
