### ISSUE TITLE
Parameters not unique for objects

### ISSUE THREAD

**Issue by mickkn** [zhelyabuzhsky/stockfish#59]
Hi, I'm using the script with 2 sub processes, one running some eval and some running an AI. But it seems that there is bug somewhere with the get_parameters() function. The parameters are shared between objects.

Running this test, pretty much shows the problem

    def test_get_parameters(self):

        s1 = Stockfish()
        s2 = Stockfish()

        arg1 = s1.get_parameters()
        arg2 = s2.get_parameters()

        assert arg1 == arg2

        s1.set_skill_level(1)

        arg1 = s1.get_parameters()
        arg2 = s2.get_parameters()

        assert arg1 != arg2

**Comment by VivekThazhathattil** [comment]
Hi! The issue was that `DEFAULT_STOCKFISH_PARAMS` was declared globally. 
So `self._parameters = DEFAULT_STOCKFISH_PARAMS` simply means that `self._parameters` is referring to the same memory location used by `DEFAULT_STOCKFISH_PARAMS`  regardless of it being part of different objects. I've created a pull request which I think rectifies the problem. Please review it.. :)
