### ISSUE TITLE
Bad values, and inconsistency due to tendency to 2.57

### ISSUE THREAD

**Issue by dakshsriv** [zhelyabuzhsky/stockfish#69]
I have found that the get_evaluation is getting cp values that has tendency to 2.57. Here are the runs: [TestCase1Results.txt](https://github.com/zhelyabuzhsky/stockfish/files/7148279/TestCase1Results.txt).
Here is the code that was run:
[moveAnalyze-in-txt.txt](https://github.com/zhelyabuzhsky/stockfish/files/7148280/moveAnalyze-in-txt.txt), where I called getStats() with the fen and move specified in the test case files. 

I used [stockfish module version 3.17.0](https://pypi.org/project/stockfish/3.17.0/) and [stockfish 14](https://stockfishchess.org/blog/2021/stockfish-14/) on Elementary OS 5.1 Hera (Ubuntu 18.04 base). 

The results were also not the values given by [lichess.org](https://lichess.org). Can someone please explain what's wrong and/or how to fix it?

**Comment by fsmosca** [comment]
@dakshsriv
I see that you define stockfish with:
```
stockfish = Stockfish("Engines/stockfish_14_linux_x64/stockfish_14_x64")
stockfish = Stockfish(parameters={"Threads": 3, "Minimum Thinking Time": 100, "Ponder": True})
```
and you are using `stockfish_14_x64`.

By default stockfish will search at depth=2. Also the parameter Minimum Thinking Time will not work because you are using stockfish 14, it is only for stockfish 11 and lower.

The method `get_top_moves(3)` also searches to only depth=2.

To increase search time, just increase search depth. Example.
```python
stockfish = Stockfish(
    "Engines/stockfish_14_linux_x64/stockfish_14_x64",
    depth=20,
    parameters={"Threads": 3, "Ponder": True}
)

eval = stockfish.get_evaluation()  # stockfish will search to depth 20
topmoves = stockfish.get_top_moves(3)   # stockfish will search to depth 20
```

Depth can also be updated with:
```python
stockfish = Stockfish(
    "Engines/stockfish_14_linux_x64/stockfish_14_x64",
    depth=20,
    parameters={"Threads": 3, "Ponder": True}
)
stockfish.depth = 30
eval = stockfish.get_evaluation()  # stockfish will search to depth 30
```
