### ISSUE TITLE
Crashing when using Stockfish 15

### ISSUE THREAD

**Issue by doodledood** [zhelyabuzhsky/stockfish#90]
The function `self._get_stockfish_major_version` is crashing when using the latest stockfish. They probably changed the output a bit.

**Comment by johndoknjas** [comment]
Hi, for the function crashing do you mean the "test_get_stockfish_major_version" function in test_models.py crashes?

**Comment by johndoknjas** [comment]
@doodledood Hmm, alright. For the test failing it made sense since 15 for the major version wasn't included yet as one of the acceptable outputs. For the actual function though it works for me, and running SF 15 by itself seems to use the same output format as SF 14. Do you know if it works for you on SF 14?

**Comment by doodledood** [comment]
Yeah, I'm running it perfectly with stockfish 14.1

**Comment by janfranchini** [comment]
> For the actual function though it works for me
>
Same. 

> It crashed when trying to get the major version, which fails for Stockfish 15 (at least on my machine).
>
@doodledood do you have some additional info as returned errors or similar that can help understanding where is the problem?

**Comment by doodledood** [comment]
So using the latest stockfish 15 (stockfish_15_linux_x64_avx2) this is what
I'm getting when running it on Debian-based Linux:

`ValueError: invalid literal for int() with base 10:
'/lib/x86_64-linux-gnu/libc'`

In this file:

`File "/usr/local/lib/python3.9/site-packages/stockfish/models.py", line
48, in __init__
      self._stockfish_major_version: int = int(...`

As a side note, I get the same error for all stockfish 15 Linux versions,
not just avx2

**Comment by janfranchini** [comment]
There should be a `'15'` string instead of `'/lib/x86_64-linux-gnu/libc'`. These strings are coming from the first output line of the stockfish engine (stderr gets here too since `stderr=subprocess.STDOUT` option is set). 

Have you tried to run the engine itself from the command line? The first output line should be something like this:
```
Stockfish 15 by the Stockfish developers (see AUTHORS file)
```
Maybe you're getting an error as a first line and this wrapper tries to parse it without getting what it would expect.

**Comment by doodledood** [comment]
@johndoknjas Compiling Stockfish 15 directly from the source worked like a charm. Thanks!
