### ISSUE TITLE
Error in stockfish\models.py in __del__, _put

### ISSUE THREAD

**Issue by pain0LY** [zhelyabuzhsky/stockfish#91]
I did not even use __del__ I dont know why it is error'ing there.
The exact line which is error'ing is, stdin.flush()
It gives OSError: [Errorno 22] Invalid argument. 
I have a different computer where I do not get the error.
I dont understand.

![image](https://user-images.githubusercontent.com/104758879/166207110-f4f32507-c084-43d1-8694-80a6fb5f12e2.png)

![Bild_2022-05-02_103426413](https://user-images.githubusercontent.com/104758879/166207016-895ca1d4-21c8-489a-b7c2-6ee5a88a0a61.png)

**Comment by johndoknjas** [comment]
Hi, not sure why it's giving you that error. For the __del__ method though, it will generally be called implicitly once you're finished with your object of the Stockfish class (so e.g., when your python script finishes). It will run without you calling it.

For your problem, this question seems to deal with something similar (just stdin.write instead of stdin.flush):
https://stackoverflow.com/questions/23688492/oserror-errno-22-invalid-argument-in-subprocess

In your code are you doing anything to kill the self._stockfish subprocess yourself? Maybe that's what's causing the issue.

**Comment by pain0LY** [comment]
hi brother. ye i have the obejct inside a loop xd. so he overwrites it all the time? and probably does the del function. no i dont use the kill stockfish at all. BUT bro I now updated from python 3.7 to 3.9 and also used stockfish 14 instead of 11 and also I use the stockfish __del__ function after the loop. now everything works. these are a lot of updates to i dont know which one solved it :D
